### ISSUE TITLE
Adapter is detected on Acer Laptop with firmware install but not functional

### ISSUE THREAD

**Issue by enyung** [samveen/mt7902-dkms#9]
Testing on Acer Aspire A314-23P.

![image](https://github.com/samveen/mt7902-dkms/assets/14142821/251d9289-d6db-4b2c-ae33-010237f8a27f)

With the MT7921 driver and Acer's firmware installed, the network adapter seems to be recognized but is still not functional. 

![image](https://github.com/samveen/mt7902-dkms/assets/14142821/bc06e3cc-9a5e-4ee2-bda8-f065455575c8)

Tested on Ubuntu Noble Numbat with the 6.8 kernel. I am willing to provide any help needed.

**Comment by samveen** [comment]
@enyung Thank you for your offer to help. I've just merged a large PR by @DarkMatter-999 . Would you please help test it?

**Comment by enyung** [comment]
I loaded the new PR and I am getting the same "Failed to get patch semaphore" message as in #8 . 

`[   18.087708] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   18.087719] mt7902 0000:02:00.0: Message 00000010 (seq 5) timeout
[   18.087735] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   18.087746] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   18.087755] mt7902 0000:02:00.0: Failed to get patch semaphore
[   18.163179] mt7902 0000:02:00.0: Entering mt7902_mt76_connac_mcu_patch_sem_ctrl function
[   18.163199] mt7902 0000:02:00.0: Calling mt7902_mt76_mcu_send_message with params 1
[   18.163209] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   18.163241] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 00000000556c4729 
[   18.163253] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   18.163270] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   18.163280] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294688388
[   18.163289] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294688388
[   18.163297] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 3000
[   21.222823] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   21.222857] Workqueue: events mt7902_init_work [mt7902_common]
[   21.222954]  mt7902_mt76_mcu_get_response+0xb6/0x1a0 [mt7902_common]
[   21.223017]  mt7902_mt76_mcu_skb_send_and_get_msg+0xf7/0x1d0 [mt7902_common]
[   21.223067]  mt7902_mt76_mcu_send_and_get_msg+0xcf/0x100 [mt7902_common]
[   21.223118]  mt7902_mt76_connac2_load_patch+0xa2/0x3a0 [mt7902_common]
[   21.223182]  mt7902_mt792x_load_firmware+0x43/0x1a0 [mt7902_common]
[   21.223231]  mt7902_run_firmware+0x2d/0x5e0 [mt7902_common]
[   21.223287]  ? mt7902_rr+0x26/0x40 [mt7902]
[   21.223307]  ? ____mt7902_mt76_poll_msec+0x79/0xd0 [mt7902_common]
[   21.223361]  mt7902e_mcu_init+0x50/0x90 [mt7902]
[   21.223374]  mt7902_init_work+0x54/0x230 [mt7902_common]
[   21.223620] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   21.223624] mt7902 0000:02:00.0: Message 00000010 (seq 6) timeout
[   21.223628] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   21.223631] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   21.223633] mt7902 0000:02:00.0: Failed to get patch semaphore
[   21.297944] mt7902 0000:02:00.0: Entering mt7902_mt76_connac_mcu_patch_sem_ctrl function
[   21.297962] mt7902 0000:02:00.0: Calling mt7902_mt76_mcu_send_message with params 1
[   21.297973] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   21.298002] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 0000000054c046b1 
[   21.298014] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   21.298031] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   21.298041] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294691523
[   21.298050] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294691523
[   21.298059] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 3000
[   24.358965] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   24.359014] Workqueue: events mt7902_init_work [mt7902_common]
[   24.359162]  mt7902_mt76_mcu_get_response+0xb6/0x1a0 [mt7902_common]
[   24.359266]  mt7902_mt76_mcu_skb_send_and_get_msg+0xf7/0x1d0 [mt7902_common]
[   24.359350]  mt7902_mt76_mcu_send_and_get_msg+0xcf/0x100 [mt7902_common]
[   24.359434]  mt7902_mt76_connac2_load_patch+0xa2/0x3a0 [mt7902_common]
[   24.359540]  mt7902_mt792x_load_firmware+0x43/0x1a0 [mt7902_common]
[   24.359622]  mt7902_run_firmware+0x2d/0x5e0 [mt7902_common]
[   24.359713]  ? mt7902_rr+0x26/0x40 [mt7902]
[   24.359747]  ? ____mt7902_mt76_poll_msec+0x79/0xd0 [mt7902_common]
[   24.359836]  mt7902e_mcu_init+0x50/0x90 [mt7902]
[   24.359858]  mt7902_init_work+0x54/0x230 [mt7902_common]
[   24.360165] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   24.360176] mt7902 0000:02:00.0: Message 00000010 (seq 7) timeout
[   24.360194] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   24.360206] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   24.360214] mt7902 0000:02:00.0: Failed to get patch semaphore
[   24.428172] mt7902 0000:02:00.0: Entering mt7902_mt76_connac_mcu_patch_sem_ctrl function
[   24.428191] mt7902 0000:02:00.0: Calling mt7902_mt76_mcu_send_message with params 1
[   24.428202] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   24.428232] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 00000000ffa54400 
[   24.428244] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   24.428262] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   24.428271] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294694653
[   24.428280] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294694653
[   24.428288] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 3000
[   27.430848] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   27.430894] Workqueue: events mt7902_init_work [mt7902_common]
[   27.431037]  mt7902_mt76_mcu_get_response+0xb6/0x1a0 [mt7902_common]
[   27.431133]  mt7902_mt76_mcu_skb_send_and_get_msg+0xf7/0x1d0 [mt7902_common]
[   27.431212]  mt7902_mt76_mcu_send_and_get_msg+0xcf/0x100 [mt7902_common]
[   27.431290]  mt7902_mt76_connac2_load_patch+0xa2/0x3a0 [mt7902_common]
[   27.431390]  mt7902_mt792x_load_firmware+0x43/0x1a0 [mt7902_common]
[   27.431466]  mt7902_run_firmware+0x2d/0x5e0 [mt7902_common]
[   27.431551]  ? mt7902_rr+0x26/0x40 [mt7902]
[   27.431583]  ? ____mt7902_mt76_poll_msec+0x79/0xd0 [mt7902_common]
[   27.431666]  mt7902e_mcu_init+0x50/0x90 [mt7902]
[   27.431687]  mt7902_init_work+0x54/0x230 [mt7902_common]
[   27.431977] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   27.431988] mt7902 0000:02:00.0: Message 00000010 (seq 8) timeout
[   27.432004] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   27.432015] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   27.432023] mt7902 0000:02:00.0: Failed to get patch semaphore
[   27.500978] mt7902 0000:02:00.0: Entering mt7902_mt76_connac_mcu_patch_sem_ctrl function
[   27.500998] mt7902 0000:02:00.0: Calling mt7902_mt76_mcu_send_message with params 1
[   27.501009] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   27.501036] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 000000001455fc34 
[   27.501048] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   27.501060] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   27.501070] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294697726
[   27.501079] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294697726
[   27.501088] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 3000
[   30.502687] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   30.502733] Workqueue: events mt7902_init_work [mt7902_common]
[   30.502877]  mt7902_mt76_mcu_get_response+0xb6/0x1a0 [mt7902_common]
[   30.502975]  mt7902_mt76_mcu_skb_send_and_get_msg+0xf7/0x1d0 [mt7902_common]
[   30.503053]  mt7902_mt76_mcu_send_and_get_msg+0xcf/0x100 [mt7902_common]
[   30.503132]  mt7902_mt76_connac2_load_patch+0xa2/0x3a0 [mt7902_common]
[   30.503231]  mt7902_mt792x_load_firmware+0x43/0x1a0 [mt7902_common]
[   30.503308]  mt7902_run_firmware+0x2d/0x5e0 [mt7902_common]
[   30.503393]  ? mt7902_rr+0x26/0x40 [mt7902]
[   30.503426]  ? ____mt7902_mt76_poll_msec+0x79/0xd0 [mt7902_common]
[   30.503508]  mt7902e_mcu_init+0x50/0x90 [mt7902]
[   30.503529]  mt7902_init_work+0x54/0x230 [mt7902_common]
[   30.503815] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   30.503826] mt7902 0000:02:00.0: Message 00000010 (seq 9) timeout
[   30.503843] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   30.503854] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   30.503862] mt7902 0000:02:00.0: Failed to get patch semaphore
[   30.580713] mt7902 0000:02:00.0: Entering mt7902_mt76_connac_mcu_patch_sem_ctrl function
[   30.580731] mt7902 0000:02:00.0: Calling mt7902_mt76_mcu_send_message with params 1
[   30.580741] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   30.580767] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 00000000785f4732 
[   30.580778] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   30.580794] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   30.580805] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294700806
[   30.580814] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294700806
[   30.580823] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 3000
[   33.638855] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   33.638900] Workqueue: events mt7902_init_work [mt7902_common]
[   33.639041]  mt7902_mt76_mcu_get_response+0xb6/0x1a0 [mt7902_common]
[   33.639138]  mt7902_mt76_mcu_skb_send_and_get_msg+0xf7/0x1d0 [mt7902_common]
[   33.639216]  mt7902_mt76_mcu_send_and_get_msg+0xcf/0x100 [mt7902_common]
[   33.639294]  mt7902_mt76_connac2_load_patch+0xa2/0x3a0 [mt7902_common]
[   33.639393]  mt7902_mt792x_load_firmware+0x43/0x1a0 [mt7902_common]
[   33.639469]  mt7902_run_firmware+0x2d/0x5e0 [mt7902_common]
[   33.639555]  ? mt7902_rr+0x26/0x40 [mt7902]
[   33.639587]  ? ____mt7902_mt76_poll_msec+0x79/0xd0 [mt7902_common]
[   33.639669]  mt7902e_mcu_init+0x50/0x90 [mt7902]
[   33.639690]  mt7902_init_work+0x54/0x230 [mt7902_common]
[   33.639982] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   33.639994] mt7902 0000:02:00.0: Message 00000010 (seq 10) timeout
[   33.640010] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   33.640022] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   33.640029] mt7902 0000:02:00.0: Failed to get patch semaphore
[   33.711085] mt7902 0000:02:00.0: hardware init failed
`

**Comment by DarkMatter-999** [comment]
Yeah same behaviour then.
The `skb` returns a null pointer i.e.`SKB info: 0000000000000000`.

Thanks for testing ✌️

**Comment by samveen** [comment]
@enyung New commits. Please test?

**Comment by moigamijunior** [comment]
I've tested the solution as described in the README on my `Acer Aspire 3` running `Ubuntu 24`. However, Linux still does not recognize the device. Is there something I might be missing or an additional step I need to take?

I can see it in `lshw -C network` like @enyung:

```
*-network DISPONÍVEL      
       descrição: Network controller
       produto: MEDIATEK Corp.
       fabricante: MEDIATEK Corp.
       ID físico: 0
       informações do barramento: pci@0000:02:00.0
       versão: 00
       largura: 64 bits
       clock: 33MHz
       capacidades: cap_list
       configuração: latency=0
       recursos: memória de E/S:7c0-7bf memória:7cf0200000-7cf02fffff memória:c0500000-c0507fff
```



I did the `modprobe` commands, but nothing happened.

**Comment by samveen** [comment]
@moigamijunior Please check kernel log for log lines from the time you ran modprobe (`sudo dmesg -T` for timestamped kernel logs), and add them to the ticket for @alesliehughes and @DarkMatter-999 to review.

**Comment by branchwag** [comment]
I am facing the same issue (trying to run this on Arch Linux ASUS Vivobook laptop). Here are my logs too if helpful. 

```
$ sudo dmesg | grep -i mt79
[    3.274816] mt7902_common: loading out-of-tree module taints kernel.
[    3.274821] mt7902_common: module verification failed: signature and/or required key missing - tainting kernel
[    3.283110] mt7902 0000:02:00.0: Direct firmware load for mediatek/WIFI_RAM_CODE_MT7902_1.bin failed with error -2
[    3.285184] mt7902 0000:02:00.0: ASIC revision: 79020000
[    3.365103] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[    3.365109] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 00000000873e3d28 
[    3.365111] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[    3.365114] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[    3.365115] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294879182
[    3.365116] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294879182
[    3.365117] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[    3.365230] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 00000000d84faa89
[    3.365236] Workqueue: events mt7902_init_work [mt7902_common]
[    3.365270]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    3.365286]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    3.365297]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    3.365313]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    3.365326]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    3.365337]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    3.365349]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[    3.365352]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    3.365383] mt7902 0000:02:00.0: SKB info: 00000000d84faa89
[    3.365384] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -11
[    3.365387] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294879182
[    3.365388] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294879182
[    3.365389] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[    6.530284] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[    6.530338] Workqueue: events mt7902_init_work [mt7902_common]
[    6.530422]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.530478]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.530516]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.530566]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.530615]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.530654]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.530700]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[    6.530708]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.530812] mt7902 0000:02:00.0: SKB info: 0000000000000000
[    6.530818] mt7902 0000:02:00.0: Message 00000010 (seq 1) timeout
[    6.530829] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[    6.530835] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[    6.530838] mt7902 0000:02:00.0: Failed to get patch semaphore
[    6.610163] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[    6.610173] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 0000000000cc22bd 
[    6.610177] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[    6.610183] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[    6.610186] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294880156
[    6.610189] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294880156
[    6.610191] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[    6.610484] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000037e98715
[    6.610503] Workqueue: events mt7902_init_work [mt7902_common]
[    6.610555]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.610588]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.610612]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.610642]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.610670]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.610694]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.610720]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[    6.610725]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    6.610788] mt7902 0000:02:00.0: SKB info: 0000000037e98715
[    6.610791] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -11
[    6.610796] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294880156
[    6.610798] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294880156
[    6.610800] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[    9.730281] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[    9.730343] Workqueue: events mt7902_init_work [mt7902_common]
[    9.730508]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.730632]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.730717]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.730831]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.730937]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.731024]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.731124]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[    9.731141]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.731370] mt7902 0000:02:00.0: SKB info: 0000000000000000
[    9.731381] mt7902 0000:02:00.0: Message 00000010 (seq 2) timeout
[    9.731401] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[    9.731412] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[    9.731419] mt7902 0000:02:00.0: Failed to get patch semaphore
[    9.815686] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[    9.815707] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 00000000324a453d 
[    9.815714] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[    9.815725] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[    9.815730] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294881117
[    9.815734] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294881117
[    9.815738] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[    9.816038] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 000000009bae5b26
[    9.816074] Workqueue: events mt7902_init_work [mt7902_common]
[    9.816162]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.816217]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.816256]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.816306]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.816355]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.816394]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.816439]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[    9.816447]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[    9.816552] mt7902 0000:02:00.0: SKB info: 000000009bae5b26
[    9.816557] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -11
[    9.816566] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294881117
[    9.816570] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294881117
[    9.816573] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   12.930000] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   12.930014] Workqueue: events mt7902_init_work [mt7902_common]
[   12.930061]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   12.930082]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   12.930097]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   12.930115]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   12.930133]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   12.930148]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   12.930165]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   12.930169]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   12.930209] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   12.930211] mt7902 0000:02:00.0: Message 00000010 (seq 3) timeout
[   12.930215] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   12.930217] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   12.930219] mt7902 0000:02:00.0: Failed to get patch semaphore
[   13.009548] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   13.009554] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 000000002bc99efa 
[   13.009556] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   13.009559] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   13.009560] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294882075
[   13.009561] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294882075
[   13.009562] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   13.009699] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 00000000369ad450
[   13.009705] Workqueue: events mt7902_init_work [mt7902_common]
[   13.009736]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   13.009753]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   13.009764]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   13.009779]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   13.009792]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   13.009803]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   13.009816]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   13.009818]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   13.009849] mt7902 0000:02:00.0: SKB info: 00000000369ad450
[   13.009851] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -11
[   13.009853] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294882075
[   13.009854] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294882075
[   13.009854] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   16.130104] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   16.130115] Workqueue: events mt7902_init_work [mt7902_common]
[   16.130147]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.130163]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.130174]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.130188]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.130201]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.130212]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.130224]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   16.130226]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.130256] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   16.130258] mt7902 0000:02:00.0: Message 00000010 (seq 4) timeout
[   16.130262] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   16.130263] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   16.130264] mt7902 0000:02:00.0: Failed to get patch semaphore
[   16.209932] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   16.209938] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 0000000036f857ce 
[   16.209940] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   16.209944] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   16.209945] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294883035
[   16.209946] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294883035
[   16.209947] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   16.210238] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 00000000f813f979
[   16.210245] Workqueue: events mt7902_init_work [mt7902_common]
[   16.210273]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.210289]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.210300]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.210314]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.210327]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.210338]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.210350]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   16.210353]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   16.210382] mt7902 0000:02:00.0: SKB info: 00000000f813f979
[   16.210384] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -11
[   16.210386] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294883035
[   16.210387] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294883035
[   16.210388] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 899
[   19.330225] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   19.330265] Workqueue: events mt7902_init_work [mt7902_common]
[   19.330374]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.330444]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.330494]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.330559]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.330619]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.330670]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.330727]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   19.330737]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.330870] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   19.330878] mt7902 0000:02:00.0: Message 00000010 (seq 5) timeout
[   19.330891] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   19.330897] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   19.330902] mt7902 0000:02:00.0: Failed to get patch semaphore
[   19.411102] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   19.411117] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 00000000f366eb88 
[   19.411123] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   19.411131] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   19.411135] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294883996
[   19.411139] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294883996
[   19.411141] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   19.411322] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 000000001f6cbf0f
[   19.411346] Workqueue: events mt7902_init_work [mt7902_common]
[   19.411420]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.411466]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.411498]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.411539]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.411578]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.411610]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.411647]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   19.411654]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   19.411739] mt7902 0000:02:00.0: SKB info: 000000001f6cbf0f
[   19.411744] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -11
[   19.411751] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294883996
[   19.411754] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294883996
[   19.411756] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   22.530244] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   22.530307] Workqueue: events mt7902_init_work [mt7902_common]
[   22.530477]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.530601]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.530685]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.530799]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.530906]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.530994]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.531093]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   22.531110]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.531341] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   22.531353] mt7902 0000:02:00.0: Message 00000010 (seq 6) timeout
[   22.531373] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   22.531384] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   22.531391] mt7902 0000:02:00.0: Failed to get patch semaphore
[   22.614851] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   22.614872] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 00000000395f058a 
[   22.614879] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   22.614890] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   22.614895] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294884957
[   22.614898] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294884957
[   22.614901] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   22.615131] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 00000000d00efa08
[   22.615158] Workqueue: events mt7902_init_work [mt7902_common]
[   22.615240]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.615290]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.615325]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.615370]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.615414]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.615449]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.615489]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   22.615496]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   22.615642] mt7902 0000:02:00.0: SKB info: 00000000d00efa08
[   22.615648] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -11
[   22.615656] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294884957
[   22.615659] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294884957
[   22.615662] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   25.730176] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   25.730209] Workqueue: events mt7902_init_work [mt7902_common]
[   25.730300]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.730351]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.730386]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.730431]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.730475]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.730511]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.730552]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   25.730558]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.730654] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   25.730660] mt7902 0000:02:00.0: Message 00000010 (seq 7) timeout
[   25.730669] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   25.730673] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   25.730677] mt7902 0000:02:00.0: Failed to get patch semaphore
[   25.811566] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   25.811620] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 00000000bb3e4137 
[   25.811626] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   25.811638] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   25.811642] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294885916
[   25.811646] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294885916
[   25.811649] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   25.811935] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000087804a30
[   25.811970] Workqueue: events mt7902_init_work [mt7902_common]
[   25.812049]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.812100]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.812136]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.812182]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.812225]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.812261]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.812302]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   25.812309]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   25.812405] mt7902 0000:02:00.0: SKB info: 0000000087804a30
[   25.812411] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -11
[   25.812419] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294885916
[   25.812423] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294885916
[   25.812426] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   28.930029] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   28.930039] Workqueue: events mt7902_init_work [mt7902_common]
[   28.930068]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   28.930084]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   28.930095]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   28.930108]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   28.930122]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   28.930133]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   28.930145]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   28.930147]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   28.930177] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   28.930179] mt7902 0000:02:00.0: Message 00000010 (seq 8) timeout
[   28.930182] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   28.930183] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   28.930184] mt7902 0000:02:00.0: Failed to get patch semaphore
[   29.009604] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   29.009611] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 00000000526c22d0 
[   29.009613] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   29.009615] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   29.009617] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294886875
[   29.009618] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294886875
[   29.009619] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   29.009735] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 00000000db2f10d5
[   29.009742] Workqueue: events mt7902_init_work [mt7902_common]
[   29.009772]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   29.009787]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   29.009798]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   29.009812]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   29.009825]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   29.009836]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   29.009848]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   29.009851]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   29.009880] mt7902 0000:02:00.0: SKB info: 00000000db2f10d5
[   29.009881] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -11
[   29.009883] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294886875
[   29.009884] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294886875
[   29.009885] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   32.130202] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   32.130238] Workqueue: events mt7902_init_work [mt7902_common]
[   32.130327]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.130385]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.130423]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.130474]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.130522]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.130561]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.130606]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   32.130614]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.130720] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   32.130726] mt7902 0000:02:00.0: Message 00000010 (seq 9) timeout
[   32.130736] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   32.130741] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   32.130744] mt7902 0000:02:00.0: Failed to get patch semaphore
[   32.212405] mt7902 0000:02:00.0: Entering mt7902_mt76_mcu_send_and_get_msg cmd: 16
[   32.212420] mt7902 0000:02:00.0: mt7902_mt76_mcu_msg_alloc 00000000455628ca 
[   32.212425] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg acquiring mutex
[   32.212434] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg cmd: 16, ret: 0, wait_resp: 1
[   32.212438] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294887836
[   32.212441] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294887836
[   32.212443] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   32.212703] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 000000002279950c
[   32.212732] Workqueue: events mt7902_init_work [mt7902_common]
[   32.212807]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.212853]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.212886]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.212927]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.212964]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.212993]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.213028]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   32.213033]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   32.213113] mt7902 0000:02:00.0: SKB info: 000000002279950c
[   32.213117] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -11
[   32.213124] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg expires: 4294887836
[   32.213127] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response expires: 4294887836
[   32.213130] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response timeout: 900
[   34.221463] usbcore: registered new interface driver mt7921u
[   34.234842] mt7921u 1-3:1.0: HW/SW Version: 0x8a108a10, Build Time: 20240716150944a
[   34.509528] mt7921u 1-3:1.0: WM Firmware Version: ____010000, Build Time: 20240716151027
[   35.330185] mt7902 0000:02:00.0: mt7902_mt76_mcu_get_response ret: 0000000000000000
[   35.330218] Workqueue: events mt7902_init_work [mt7902_common]
[   35.330307]  mt7902_mt76_mcu_get_response+0x146/0x16f [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   35.330363]  mt7902_mt76_mcu_skb_send_and_get_msg.cold+0x44/0xc1 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   35.330402]  mt7902_mt76_connac2_load_patch+0x79/0x110 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   35.330453]  mt7902_mt792x_load_firmware+0x50/0x160 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   35.330500]  mt7902_run_firmware+0x2d/0x3d0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   35.330540]  ? ____mt7902_mt76_poll_msec+0x72/0xb0 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   35.330585]  mt7902e_mcu_init+0x65/0xa0 [mt7902 73711490824ff01b53e7f6d6868b70f8f8313773]
[   35.330593]  mt7902_init_work+0x37/0x170 [mt7902_common 5a3037b2f3f3fb5be8e3adb1a7f8fb51c83e89ac]
[   35.330698] mt7902 0000:02:00.0: SKB info: 0000000000000000
[   35.330703] mt7902 0000:02:00.0: Message 00000010 (seq 10) timeout
[   35.330713] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg > mcu_parse_response cmd: 16, ret: -110
[   35.330718] mt7902 0000:02:00.0: mt7902_mt76_mcu_skb_send_and_get_msg unlocking mutex
[   35.330722] mt7902 0000:02:00.0: Failed to get patch semaphore
[   35.408779] mt7902 0000:02:00.0: hardware init failed

```
